<a href="https://colab.research.google.com/github/Aman-Data-wizard/Machine-Learning/blob/main/pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Aman Lal
#Erp Id: 0231bca008
import pandas as pd

In [4]:
data = pd.read_excel('/content/ML_2.xlsx')

In [5]:
data.head()

Marks  CGPA
0   50.0   5.0
1   60.0   6.0
2    NaN   7.0
3   80.0   NaN
4   90.0   9.0

In [10]:
data['Marks'] = data['Marks'].fillna(data['Marks'].mean())
data['CGPA'] = data['CGPA'].fillna(data['CGPA'].mean())
data.tail(3)

Marks  CGPA
2   70.0  7.00
3   80.0  6.75
4   90.0  9.00

In [13]:
marks = data[['Marks']]
cgpa = data['CGPA']

In [ ]:
#Ml Model processing

In [14]:
from sklearn.linear_model import LinearRegression



model = LinearRegression()
model.fit(marks,cgpa)
result = model.predict([[20]])
print("Predicted CGPA: ", result)

In [16]:
#PCA feature reduction technique
import numpy as np


In [27]:
fish = np.array([[200,100,5],[190,90,5], [100,90,3],[90,70,3]])
type = np.array([0,0,1,1])  #0 salmon #1 catfish
fish


array([[200, 100,   5],
       [190,  90,   5],
       [100,  90,   3],
       [ 90,  70,   3]])

In [19]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [29]:
scaler = StandardScaler()
fish_scaler  = scaler.fit_transform(fish)
pca = PCA(n_components=3)
fish_pca = pca.fit_transform(fish_scaler)
print("PCA: ", pca.explained_variance_ratio_)
print("fish_pca: ", fish_pca)

PCA:  [8.77339263e-01 1.22481130e-01 1.79607518e-04]
fish_pca:  [[ 1.86441644  0.19211942  0.0291673 ]
 [ 1.25749876 -0.52193426 -0.02988768]
 [-1.01435808  0.90856708 -0.01397554]
 [-2.10755712 -0.57875225  0.01469591]]
